name: Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Mintlify CLI
        run: npm install -g @mintlify/cli
        
      - name: Check for broken links
        run: mintlify broken-links
        
      - name: Deploy to Mintlify
        if: github.ref == 'refs/heads/main'
        env:
          MINTLIFY_API_KEY: ${{ secrets.MINTLIFY_API_KEY }}
        run: |
          mintlify deploy --api-key=$MINTLIFY_API_KEY